SuperMarkIT/SuperMarkIT/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name="about"),
    path('', views.homepage, name="home"),
    path('basket/', include("basket.urls")),
    path('products/', include("products.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SuperMarkIT/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = "basket"

urlpatterns = [
    path('basket/', views.basket_view, name="basket"),
    re_path(r'(?P<slug>[\w-]+)/', views.update_basket, name="update")
]

SuperMarkIT/basket/models.py
from django.db import models
from products.models import Product
# Create your models here.


class Basket(models.Model):
    total_tesco = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    total_sainsburys = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    total_morrisons = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "Cart id: {}".format(self.id)


class BasketItem(models.Model):
    basket = models.ForeignKey(Basket, null=True, blank=True, on_delete=models.CASCADE)
    # Basket foriegn key
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    product_total = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    # product total
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        try:
            return str(self.basket.id)
        except AttributeError:
            return self.product.name

SuperMarkIT/basket/views.py
from django.shortcuts import render, HttpResponseRedirect

# Create your views here.
from products.models import Product

from .models import Basket, BasketItem


def basket_view(request):
    try:
        session_id = request.session["basket_id"]
    except KeyError:
        session_id = None

    if session_id:
        basket = Basket.objects.get(id=session_id)
        context = {"basket": basket}
    else:
        empty_message = "Your basket is currently empty"
        context = {"empty": True, "empty_message": empty_message}

    template = "basket/basket-view.html"
    return render(request, template, context)


def update_basket(request, slug):
    # session expires after x seconds of inactivity
    request.session.set_expiry(1800)
    try:
        quantity = request.GET.get("quantity")
        update_quantity = True
    except ValueError:
        quantity = None
        update_quantity = False

    # Get if cart exists. if not create a new one.
    try:
        session_id = request.session["basket_id"]
    except KeyError:
        new_basket = Basket()
        new_basket.save()
        request.session["basket_id"] = new_basket.id
        session_id = new_basket.id

    basket = Basket.objects.get(id=session_id)

    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        pass

    # the below returns ("Basket item object", "true/false")
    basket_item, created = BasketItem.objects.get_or_create(basket=basket, product=product)


    if quantity and update_quantity:
        if int(quantity) <= 0:
            basket_item.delete()
        else:
            basket_item.quantity = quantity
            basket_item.save()
    else:
        pass

    start_total_tesco = 0.00
    start_total_sainsburys = 0.00
    start_total_morrisons = 0.00

    for item in basket.basketitem_set.all():
        product_total_tesco = float(item.product.price_tesco) * item.quantity
        product_total_sainsburys = float(item.product.price_sainsburys) * item.quantity
        product_total_morrisons = float(item.product.price_morrisons) * item.quantity
        start_total_tesco += product_total_tesco
        start_total_sainsburys += product_total_sainsburys
        start_total_morrisons += product_total_morrisons

    request.session["items_total"] = basket.basketitem_set.count()
    # print(basket.basketitem_set.count())

    basket.total_tesco = start_total_tesco
    basket.total_sainsburys = start_total_sainsburys
    basket.total_morrisons = start_total_morrisons

    basket.save()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

SuperMarkIT/basket/templates/basket/basket-view.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}
<head>
  <meta charset="utf-8">
  <title>Basket</title>
  <link rel="stylesheet" href="{% static 'basket/basket-page.css' %}">
</head>
{% if empty %}

<h2>{{ empty_message }}</h2>

{% else %}

<div class="heading-basket">
  <h1>Your Basket</h1>
</div>

<div class="col-sm-8 col-sm-offset-2">


<table class="table">
  <tr>
    <th>Product</th>
    <th>Product Name</th>
    <th><span class="tesco-hdr"><img src="{% static 'basket/tesco-logo.png'%}" alt="Tesco Logo"></span></th>
    <th><span class="sainsburys-hdr"><img src="{% static 'basket/sainsburys-logo.png'%}" alt="Sainsburys Logo"></span></th>
    <th><span class="morrisons-hdr"><img src="{% static 'basket/morrisons-logo.png'%}" alt="morrisons Logo"></span></th>
    <th>Quantity</th>
    <th></th>
  </tr>
  {% for item in basket.basketitem_set.all %}

  <tr>
    <td width="102"><img src="{{item.product.thumbnail.url}}" class="basket-thumbnails" width="100" height="100" ></td>
    <td>{{item.product.name}}</td>
    <td>£{{item.product.price_tesco}}</td>
    <td>£{{item.product.price_sainsburys}}</td>
    <td>£{{item.product.price_morrisons}}</td>
    <td>{{item.quantity}}</td>
    <td><a href="{% url 'basket:update' item.product.slug %}?quantity=0" class="remove-from-basket">Remove</a></td>
  </tr>
  {% endfor %}
  <tfoot>
    <td>Totals</td>
    <td></td>
    <td>£{{basket.total_tesco}}</td>
    <td>£{{basket.total_sainsburys}}</td>
    <td>£{{basket.total_morrisons}}</td>
    <td></td>
    <td>

    </td>
  </tfoot>
</table>

</div>
{% endif %}

{% endblock %}