SuperMarkIT/SuperMarkIT/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name="about"),
    path('', views.homepage, name="home"),
    path('basket/', include("basket.urls")),
    path('products/', include("products.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SuperMarkIT/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
 path('register/', views.register_page, name="register"),
 path('login/', views.login_page, name="login"),
 path('logout/', views.logout_page, name="logout")
]

SuperMarkIT/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = "basket"

urlpatterns = [
    path('basket/', views.basket_view, name="basket"),
    re_path(r'(?P<slug>[\w-]+)/', views.update_basket, name="update")
]

SuperMarkIT/products/urls.py
from django.urls import path, re_path
from . import views

app_name = "products"

urlpatterns = [
    path('main/', views.main_products, name="main"),
    path('categories/', views.categories, name="categories"),
    re_path(r'categories/(?P<category_slug>[-\w]+)/', views.filtered_products, name="filtered_products"),
]

SuperMarkIT/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}

  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body style="background-color: #d0eaf2; color: #1f4070;">
    <h1>Created by Aishwarya Sakunde & Arti Singh</h1>
    <pre><span class="about-content" style="font-size: 18px;">
      SuperMarkIt is a website that uses webscraping code written in Python
      to compare the prices of grocery products across the UK's leading
      supermarkets.

      To use the webscraper the SuperUser creates the product and gives it a
      Category and Name. In this same section the URL for each supermarket
      is then entered and stored into the database. Once the load-prices.py file
      is ran it will go through each URL in the database and scrape the prices
      from each webpage. Erroneous URLs/prices will be flagged in the terminal
      to the user.

      
    </span></pre>
  </body>
{% endblock %}

SuperMarkIT/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'banner-styles.css' %}">
  </head>
  <header>
    <div class="logo-image">
      <h1><a href="{% url 'home' %}"><img src="{% static 'Logo-main1.png'%}" alt="SuperMarkIt"/></a></h1>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'products:categories' %}" class="tag-categories-base">Categories</a></li>
          <li><a href="{% url 'products:main' %}" class="tag-products-base">Products</a></li>
          <li><a href="{% url 'basket:basket' %}" class="tag-basket-base">Basket</a></li>
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" name="btn-logout">Logout</button>
            </form>
          </li>
        {% else %}
          <li><a href="{% url 'products:categories' %}" class="tag-categories-base">Categories</a></li>
          <li><a href="{% url 'products:main' %}" class="tag-products-base">Products</a></li>
          <li><a href="{% url 'basket:basket' %}" class="tag-basket-base">Basket</a></li>
          <li><a href="{% url 'accounts:login' %}" class="tag-login-base">Login</a></li>
          <li><a href="{% url 'accounts:register' %}" class="tag-register-base">Register</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <body>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

SuperMarkIT/templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}

<!DOCTYPE html>
{% block content %}
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'homepage-styles.css' %}">
  </head>
  <body>
    <section class="hero">
      <div class="site-description">
        <h2>Grocery shopping with a difference!</h2>
        <p>A webscraper that compares the prices of your shopping basket across the UK's largest supermarkets.</p>
        <br>
        <a href="{% url 'about' %}" class="tag-about">Find Out More!</a>
      </div>
    </section>
    <span class="created-by"><p>Created Aishwarya Sakunde and Arti Singh</p></span>
  </body>
{% endblock %}